### ISSUE TITLE
Design artifacts for BCDevExchange

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/design#1]
## Background

[bcdevexchange.org](https://bcdevexchange.org/) is the public facing site for the BC Developers' Exchange - an experiment in tech innovation and collaboration. 

We want a new overall design for both static and functional aspects of the site. The design needs to be responsive.
### Story

As a developer for the BC Developers' Exchange, I need to have design assets readily available to me so that I can develop efficiently.  This includes css styles and themes along with examples of how to use them.  It also includes standard page templates.
## How to contribute

We are offering this issue as a paid opportunity through our [experimental procurement model, Code-with-Us](https://github.com/BCDevExchange/code-with-us/wiki/Disclaimer). 

To work on this issue, we are accepting proposals until **12:00:00 PDT on Thursday, October 20, 2016**. After that time, we will evaluate the proposals we’ve received, and assign the work to one person by Friday, October 21.  [How assignment works](https://github.com/BCDevExchange/code-with-us/wiki/How-assignment-works)
### What to include in your proposal

We will evaluate and score proposals by the following **criteria**:
1. Your ability to dedicate the time needed to complete the issue by **November 4, 2016** (Mandatory).
2. The estimated date you think you can show us your first iteration (Mandatory).
3. A short (no more than 200 words) summary of your proposed approach (60 points).
4. References to your relevant experience and demonstrated ability to do the work (40 points). For example, a link to your GitHub projects.
5. With your proposal, you must attach a copy of the [Code-with-Us Terms](https://github.com/BCDevExchange/devex/blob/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf), with the required information asked for in the “Acceptance” section of the Terms inserted into the document (Mandatory).

The highest scoring proposal will get the assignment.
### How to submit your proposal

Please submit your proposal to [Meaghan.Stewart@gov.bc.ca](mailto:Meaghan.Stewart@gov.bc.ca) **before 12:00:00 PDT on Thursday, October 20, 2016**.  Please put "**Design artifacts for BCDevExchange**" in the subject line. 
## Acceptance Criteria

To be paid for this opportunity we need you to:

1) Deliver a responsive Bootstrap theme with a single page example similar to [https://getbootstrap.com/examples/theme/#
](https://getbootstrap.com/examples/theme/#)

2) Redesign the following pages using the supplied bootstrap theme with new layouts:
- [Homepage](https://bcdevexchange.org/) (You may also reference [mockup-homepage.pdf](https://github.com/BCDevExchange/design/blob/master/assets/mockup-homepage.pdf) for an example of some of the elements we’d like to include on the new homepage).
- [Program list page](https://bcdevexchange.org/programs/) 
- [Program detail page](https://bcdevexchange.org/programpages/bc-assessment.html)
- a static content page (See [mockup-content-page-long.pdf](https://github.com/BCDevExchange/design/blob/master/assets/mockup-content-page-long.pdf) for one vision of new layout)

After you submit your completed artifacts, we will review and ask you for one round of changes. After you perform the requested changes, we will accept your work and pay.

[How payment works](https://github.com/BCDevExchange/code-with-us/wiki/How-payment-works)
## Questions, Comments, Suggestions?

Please post your questions in the comments section below.

**Comment by mark-a-wilson** [comment]
Howdy folks, myself and @ccoldwell are the Opportunity Contacts for this issue. Please post any questions you have here and we'll do our best to respond promptly.

**Comment by StormTide** [comment]
Interested in this issue, but I don't have the free time to get it done by Nov 4 with my existing client load.. If no one bids, I'd consider attempting it on a no-commitment/bounty basis, but it would likely be done nearer end of November.

Also, I think I understand what you're looking for here, but scoping out the deliverable better could be useful to encourage others to bid. Do you have an example of an off-the-shelf theme that would otherwise meet the deliverable requirements you're looking for, minus the design specificity from the pdfs of course? Are you open to adapting an OpenSource (MIT/CC) theme like say one of the https://startbootstrap.com/ themes?

**Comment by mark-a-wilson** [comment]
Thanks for the comment, Kevin. We'll want to defer to folks who can get it done by Nov 4. But if that doesn't happen, we may need to extend, so feel free to stay posted.

Going to let @ccoldwell jump in regarding accepting an off-the-shelf theme. 

Just to be clear, as well, regarding: 
> encourage others to bid

we're looking for people to send their proposal per the "**What to include in your proposal**" above...but NOT looking for "bids" (i.e. lowest price) -- we're aiming to pay a fixed price of $5,000.

**Comment by dewolfe001** [comment]
I am interested in bidding on this and will try to prep a submission before tomorrow's deadline. With the talk of using Bootstrap, JQuery, etc., is there a step down the road where this design is integrated into a dynamic system (eg. a content management system) and if so, should there be attention paid to making dynamic elements (news, lists, discussions, etc.) easy to extract as part of the process of turning these three pages into templates?

**Comment by mark-a-wilson** [comment]
Further to my last comment:

### Licenses / Accepting an off-the-shelf theme
As per [this guide](https://github.com/bcgov/guide-for-open-source-projects/blob/18f-pages/_pages/Licenses.md), our preferred licenses are **Apache 2.0** and **Creative Commons**, however, if the work you give us has an **MIT** license attached, we CAN accept it.

### Approach
We would appreciate a consultative approach - i.e. you spending a bit of time to chat with us to understand the target audiences of our website and our current and future business. 

### Proposals
If you have already sent us a proposal, you are free to send revised versions up to the submission deadline, and we will review your latest one. Please just be clear so that we know what constitutes your entire proposal.

Thanks for taking the time to ask questions!

**Comment by dewolfe001** [comment]
One additional question: the mock-up PDFs have some creative elements (the icons, the exchange logo, the BC Govt logo, etc.) -- will these images be made available to successful bidder?

All the best,

Shawn

**Comment by ccoldwell** [comment]
Hi StormTide and dewolfe001! I will try to answer your questions regarding off the shelf bootstrap themes and future use as they may be somewhat related.

We intend to use the design artifacts as the basis of our revised BCDevex application, and hopefully also provide these for other application developers to use as the DevExchange grows.  So yes, these will inform interactive and functional design components.  It will be essential that they are easy to unwind or extract for use in an angular UI specifically (for our purposes).  Some of the off the shelf themes I have seen make so much use of JQuery that the adaptation to a dynamic framework is frustrating, or they constrain the developer artificially and make it hard to work in any other way than what the designer laid out.  This is partly why we are asking for only a few simple layouts that can be extrapolated into more advanced functional uses.  Please keep this in mind when considering your approach.

Great questions!

**Comment by mark-a-wilson** [comment]
Hi Shawn,
I have put the logos in the [assets folder](https://github.com/BCDevExchange/design/tree/master/assets).

**Comment by StormTide** [comment]
@ccoldwell looks like Shawn will sort it out, so I'll leave it to him. I'd be interested in seeing what the final deliverable looks like after you're done, just for clarity on deliverables for future opportunities of this type.  Maybe you can even put the resulting theme up on the BCDevX GitHub?

Re off-the-shelf though -- normally for this type of thing, I'd start off by finding an Open Source theme close to what you're looking for and then fork and customize it to meet the design requirements. No point in reinventing the wheel and all that... but I'm not clear if you're looking for 100% original work with this deliverable?

**Comment by mark-a-wilson** [comment]
@StormTide 100% original work is NOT a requirement of the Acceptance Criteria.

**Comment by mark-a-wilson** [comment]
Hello Subscribers: Just a friendly reminder to submit your proposal before **12:00:00 PDT today**. Thanks for your interest!

**Comment by dewolfe001** [comment]
Will Meaghan be sending our a confirmation of receipt of the bids?

**Comment by MeaghanRStewart** [comment]
Hi there Shawn,
Yes I will be sending out confirmations of receipt to each submission shortly.
Thanks!
Meaghan

**Comment by mark-a-wilson** [comment]
Thanks everyone who submitted a proposal. **The proposal period is now closed.** @ccoldwell and I will be reviewing them over the next day and will let you know by end of day Friday who is assigned.

**Comment by dewolfe001** [comment]
Thanks, Meaghan! Thanks, Mark!

**Comment by mark-a-wilson** [comment]
To those who submitted a proposal: a sincere thank you. The quality of the proposals you submitted exceeded our expectations.

Based on the evaluation criteria, @stephenrichter scored the highest, so we’re assigning him to work on this issue until **Nov 4**.

This is our first time trying an assignment process with a Code-with-Us opportunity. (For those who’ve been following Code-with-Us from its inception, the way it worked previously was basically that the first person to submit code that met the acceptance criteria got paid.) Our hopes are that introducing an assignment process can: 

- Reduce the risk of you doing spec work or duplicating someone else’s effort
- Provide a fair way for us to select one person to get the first crack at the work when multiple people are interested in doing it
- Require a minimal (or at least reasonable) amount of effort for you to express your interest in the work, suggest an approach, and demonstrate your capability to do it

It’s an experiment, and every time we run an opportunity, we’re looking for what works and what doesn’t, and how to improve. To that end, I would appreciate any honest and constructive feedback you have about your experience. Feel free to post your comments below, or if you’d prefer to share privately, please email me at the address on my profile.

**Comment by dewolfe001** [comment]
Congrats to @stephenrichter !
I really appreciate the consciousness to finding a way to avoid the duplication of effort. 

Mark: would you be able to share how many people submitted a proposal for this issue?

**Comment by mark-a-wilson** [comment]
Thanks Shawn. We received 6 proposals.

**Comment by stephenrichter** [comment]
Thanks @marc-a-wilson and team. I'm looking forward to working on this project, as well as provide some feedback on the Code-with-Us experience.

**Comment by mark-a-wilson** [comment]
To those others who submitted a proposal, sorry I forgot to mention on Friday....If you would like feedback on your proposal, we can provide that. Please contact me by the email address in my profile.

**Comment by mark-a-wilson** [comment]
We have got what we need now and are closing this issue. Thanks, @stephenrichter for the great work!
