### ISSUE TITLE
Program owner and developer sign up to the BCDevExchange

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/design#3]
## Background

[bcdevexchange.org](https://bcdevexchange.org/) is experimenting with a public/private collaboration framework called Code With Us where government program owners are able to post coding and other digital based opportunities.

During this iteration the BC Developers' Exchange is creating a better way for government program owners to create Code With Us opportunities, provide work context and facilitate collaboration.

Related to issues [design 1](https://github.com/BCDevExchange/design/issues/1), [design 4](https://github.com/BCDevExchange/design/issues/4), [design 5](https://github.com/BCDevExchange/design/issues/5) and 
### User Stories

As a **government program lead (owner)** I need to be able to sign up to the BC Developers' Exchange and verify who I am so that I can create my program page (and eventually projects and opportunities). 

As a **developer**, I need to sign up to the Exchange to be able to respond to opportunities.
## How to contribute

We are offering this issue as a paid opportunity through our [experimental procurement model, Code-with-Us](https://github.com/BCDevExchange/code-with-us/wiki/Disclaimer). 

To work on this issue, we are accepting proposals until **5:00 PM PDT on Monday, October 31, 2016**. After that time, we will evaluate the proposals we’ve received, and assign the work to one person by 5:00 PM PDT on Wednesday, November 2. 
### What to include in your proposal

We will evaluate and score proposals by the following **criteria**:
1. Your ability to dedicate the time needed to complete the issue by **November 14, 2016** (Mandatory).
2. The estimated date you think you can show us your first iteration (Mandatory).
3. A short (around 200 words or less would be great) summary of your proposed approach (60 points).
4. References to your relevant experience and demonstrated ability to do the work (40 points). For example, a link to your GitHub projects.
5. With your proposal, you must attach a copy of the [Code-with-Us Terms](https://github.com/BCDevExchange/devex/blob/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf), with the required information asked for in the “Acceptance” section of the Terms inserted into the document (Mandatory).

The highest scoring proposal will get the assignment. 

[How assignment works](https://github.com/BCDevExchange/code-with-us/wiki/How-assignment-works)
### How to submit your proposal

Please submit your proposal to [bcdevexchange@gov.bc.ca](mailto:bcdevexchange@gov.bc.ca) before the deadline stated above. Reference "Program owner and developer sign up to the BCDevExchange" in the subject line.
## Acceptance Criteria

To be paid for this opportunity we need you to:
1. Use the BC Developers' Exchange bootstrap theme to deliver a signup process for government program users and developers.
2. Work with the BC DevEx UX team to refine their process design.
3. Create a role based sign-up process that differentiates between government and non government users.
4. Create a system acknowledgment that users have been registered as government or non-government users. The message should also provide information regarding their permissions.
5. Use existing code as examples of setting up and configuring outgoing email notifications.
6. Ensure no duplicate users using email address as the unique identifier.
7. Work with the BC DevEx team to get content for screens and email.
8. Ensure that profile pictures work.
9. Ensure that the forgot password function is working.

[How payment works](https://github.com/BCDevExchange/code-with-us/wiki/How-payment-works)
## Questions, Comments, Suggestions?

Please post your questions in the comments section below.

**Comment by dewolfe001** [comment]
I did want to submit a proposal with the suggestion of integrating a Node.js / Mongo CMS like KeystoneJS, but I see issues 3, 4 and 5 to be linked in a serial of foundational elements with other elements added on top for the successive applications. With all three proposals closing and activating at the same time, it feels like all three proposals need the same technology strategies and specific implementations. 
I have had a MongoDB and JS background. If anyone is bidding on this and wants an extra set of eyes or hands into the work, feel free to contact me. I'd like to be involved.

**Comment by ccoldwell** [comment]
@dewolfe001, We have already considered using a CMS, and various experiments have been undertaken involving off the shelf or other open source products.  Also, the intention is to bring all the teams for these pieces of work together at the beginning to discuss approach, standards, and any overlapping functionality to ensure a cohesive product.

**Comment by paulroberts68** [comment]
Hello Subscribers: Just a friendly reminder to submit your proposal before 5:00 pm today. Thanks for your interest!

**Comment by paulroberts68** [comment]
Thank you to everyone who submitted a proposal. Based on our evaluation criteria we’re assigning this issue to Wayne Vo.

**Comment by mark-a-wilson** [comment]
After this issue was assigned to @melavo, discussion was moved here: https://github.com/BCDevExchange/devex/issues/5

We have accepted a pull request which meets our acceptance criteria, and are closing the issue.

Thanks, @melavo, for the great work!
